version: '3'
services:
  postgresqldb:
    image: postgres:9.6.11-alpine
    container_name: postgresqldb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: catalog
